### ISSUE TITLE
[Feat] BadgeView 로직 적용 및 서버 연결

### ISSUE THREAD

**Issue by Guryss** [playkuround/playkuround-iOS#114]
## 🛠 Issue
- BadgeView 로직 적용하고 서버 연결합니다. 

## 📝 To-do

- [X] 로직 적용
- [X] 서버 연결
- [x] 백그라운드 이미지에 opacity 추가 적용

**Comment by leehe228** [comment]
안녕하세요 @Guryss 

<img width="280px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/c22ee429-9ce0-4504-80f8-a3c2fde352a1"> <br/>

<img width="400px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/cec1cfaa-bb84-45ab-8b05-ee3a00b96b3e">

이전 View 작업 때 발견 못했던 내용을 알게 되어 늦었지만.... 말씀드려요!
여기 뱃지뷰 배경도 opacity가 적용되어야 할 것 같습니다...!!ㅎㅎ

**Comment by Guryss** [comment]
@leehe228 

헉 그렇네요! 해당 이슈에 반영하겠습니다 ㅎㅎ 알려주셔서 감사해유
