### ISSUE TITLE
[Feat] MyPageView 뷰 로직 적용 및 서버 API 연결

### ISSUE THREAD

**Issue by Guryss** [playkuround/playkuround-iOS#41]
## 🛠 Issue
MyPageView에 필요한 뷰 로직을 연결하고 서버 API 통신 합니다.

## 📝 To-do
- [X] 뷰 로직 연결
    - [X] fullScreenOver
    - [X] ZStack
    - [X] Instagram Link

- [X] 서버 통신 
    - [X] User Profile
    - [X] Logout
    - [X] 플쿠팀 응원하기
    - [X] 앱 버전

**Comment by leehe228** [comment]
@Guryss 이거 API들 관련해서 금일 미팅때 말씀드릴게요!
